### ISSUE TITLE
SLACK_CHANNEL env var is not optional

### ISSUE THREAD

**Issue by kentcb** [binaryberry/seal#211]
Hi,

Thanks for the great tool!

The docs make it sound like `SLACK_CHANNEL` can _optionally_ be provided as an env var, but without it I get:

```
~ $ ./bin/seal.rb qut
/app/lib/seal.rb:38:in `bark_at': undefined method `[]' for nil:NilClass (NoMethodError)
	from /app/lib/seal.rb:20:in `block in bark'
	from /app/lib/seal.rb:20:in `each'
	from /app/lib/seal.rb:20:in `bark'
	from ./bin/seal.rb:5:in `<main>'
```

This is despite having the `channel` set in my config file.

I don't know Ruby at all, but I can't help but notice it's the [only dereferencing](https://github.com/binaryberry/seal/blob/master/lib/seal.rb#L38) of `ENV` that uses double quotes instead of single. Could that be the reason?

**Comment by kentcb** [comment]
Ah, I just figured out it's because my _yml_ file was not named exactly the same as my `SEAL_ORGANISATION` env var 🤕
