### ISSUE TITLE
undefined method `[]' for nil:NilClass (NoMethodError) if not setting `SLACK_CHANNEL=`

### ISSUE THREAD

**Issue by stig** [binaryberry/seal#40]
If I follow the README and try to specify the slack channel on the command line I get this error:

    bundle exec bin/seal.rb '#seal-test' 
    /Users/stig/work/seal/lib/seal.rb:34:in `bark_at': undefined method `[]' for nil:NilClass (NoMethodError)
    	from /Users/stig/work/seal/lib/seal.rb:16:in `block in bark'
    	from /Users/stig/work/seal/lib/seal.rb:16:in `each'
    	from /Users/stig/work/seal/lib/seal.rb:16:in `bark'
    	from bin/seal.rb:5:in `<main>'

If I set SLACK_CHANNEL in the environment and just leaves out the argument it works:

    env SLACK_CHANNEL='#seal-test' bundle exec bin/seal.rb 
    {"icon_emoji":":seal_of_approval:","username":"Seal of Approval","channel":"#angry-seal-bot-test","text":"Good morning team! It's a beautiful day! :happyseal: :happyseal: :happyseal:\n\nNo pull requests to review today! :rainbow: :sunny: :metal: :tada:"}

(Although because I'm doing this locally, and the DYNO environment variable is not set, it's not using the SLACK_CHANNEL variable.)

**Comment by stig** [comment]
Hmm, I think I might have misunderstood how this works. I had not created a config file yet :-)
Things works a lot better with a config file.
